ublox_gps_node:
  ros__parameters:
    debug: 2
    device: /dev/ttyACM0
    frame_id: gps

    uart1:
      baudrate: 115200

    rate: 10.0        # 🔥 10 Hz output
    nav_rate: 1

    dynamic_model: automotive

    # Disable base station stuff (you are rover)
    tmode3: 0

    inf:
      all: true

    publish:
      nav:
        pvt: true
        relposned: true